# Production-ready Flutter Component Library
# Enhanced analysis options for optimal code quality and CDN deployment

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "dist/**"
    - "lib/generated/**"

  errors:
    # Treat these as errors for production code
    invalid_annotation_target: ignore
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    # Flutter recommended rules (included from flutter_lints)

    # Code style and formatting
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_parameters: true

    # Documentation and comments
    prefer_double_quotes: false  # Enforce single quotes
    slash_for_doc_comments: true

    # Performance and optimization
    avoid_type_to_string: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true

    # Security and best practices
    avoid_print: true  # Avoid print statements in production
    avoid_web_libraries_in_flutter: true
    parameter_assignments: true

    # Code organization
    directives_ordering: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_renaming_method_parameters: true

    # Null safety
    avoid_null_checks_in_equality_operators: true
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true

    # Modern Dart features
    unnecessary_await_in_return: true
    unnecessary_new: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true

    # String and collection operations
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true

    # Async operations
    avoid_slow_async_io: true
    cancel_subscriptions: true
    test_types_in_equals: true

    # Widget-specific rules
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    # Import and export rules
    always_use_package_imports: false  # Allow relative imports within the library
    avoid_multiple_declarations_per_line: true
    no_default_cases: true
    only_throw_errors: true
    package_prefixed_library_names: true
    type_annotate_public_apis: true
    unnecessary_library_directive: true

# Testing configuration
testing:
  test_files:
    include:
      - test/**_test.dart
    exclude:
      - test/**/*_widget_test.dart
